-- Missing extraction prompts export
-- Generated by add_missing_extraction_prompts.py

INSERT INTO pipeline_prompts 
(stage_name, prompt_text, is_active, created_by, created_at, updated_at, prompt_type, prompt_name, is_enabled)
VALUES (
    'funding_amount_extraction',
    $$Please extract the specific funding amount the startup is seeking from the pitch deck. Look for phrases like 'seeking €X', 'raising $X', 'funding requirement of X', or similar. If you find multiple amounts (seed, Series A, total, etc.), focus on the primary funding amount being sought in this round. Provide only the amount (e.g., '€2.5M', '$500K', '£1M') without additional explanation. If no specific amount is mentioned, respond with 'Not specified'.$$,
    true,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'extraction',
    'Funding Amount Extraction', 
    true
)
ON CONFLICT (stage_name) DO UPDATE SET
    prompt_text = EXCLUDED.prompt_text,
    updated_at = CURRENT_TIMESTAMP,
    prompt_name = EXCLUDED.prompt_name;

INSERT INTO pipeline_prompts 
(stage_name, prompt_text, is_active, created_by, created_at, updated_at, prompt_type, prompt_name, is_enabled)
VALUES (
    'deck_date_extraction',
    $$Please identify when this pitch deck was created or last updated. Look for dates in headers, footers, slide timestamps, version information, or any date references that indicate when the deck was prepared. Focus on the most recent date that reflects when the current version was created. Provide the date in a clear format (e.g., 'March 2024', '2024-03-15', 'Q1 2024'). If no date information is available, respond with 'Date not found'.$$,
    true,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'extraction',
    'Deck Date Extraction', 
    true
)
ON CONFLICT (stage_name) DO UPDATE SET
    prompt_text = EXCLUDED.prompt_text,
    updated_at = CURRENT_TIMESTAMP,
    prompt_name = EXCLUDED.prompt_name;