#!/bin/bash
# Script to manage Datacrunch shared filesystem

echo "🗂️ Shared Filesystem Management"
echo "=" * 50

echo "📋 Instructions for Datacrunch Dashboard:"
echo ""
echo "STEP 1: Delete Current Shared Filesystem"
echo "----------------------------------------"
echo "1. Go to Datacrunch dashboard → Shared filesystems"
echo "2. Find filesystem: SFS-5gkKcxHe (ID: 7cc261b3-b9ad-45be-8633-9f09c56a26c3)"
echo "3. Click 'Delete' to remove it completely"
echo "4. Confirm deletion"
echo ""

echo "STEP 2: Create New Shared Filesystem"
echo "------------------------------------"
echo "1. Click 'Create filesystem' button"
echo "2. Choose same settings:"
echo "   - Size: 50 GB"
echo "   - Type: NVMe"
echo "   - Location: FIN-01"
echo "3. Give it a new name: 'review-platform-v2'"
echo "4. Create the filesystem"
echo ""

echo "STEP 3: Update Configuration"
echo "-----------------------------"
echo "1. Note the new filesystem ID (will be different)"
echo "2. Note the new NFS mount command from dashboard"
echo "3. Update production server configuration:"
echo ""
echo "   # Edit .env file"
echo "   nano /opt/review-platform/backend/.env"
echo ""
echo "   # Update these values:"
echo "   DATACRUNCH_SHARED_FILESYSTEM_ID=<NEW_FILESYSTEM_ID>"
echo ""
echo "4. Update the NFS mount command in gpu_processing.py:"
echo "   nano /opt/review-platform/backend/app/services/gpu_processing.py"
echo ""
echo "   # Find line ~182 and update the mount command"
echo "   # Example: mount -t nfs -o nconnect=16 nfs.fin-01.datacrunch.io:/SFS-<NEW_ID> /mnt/shared"
echo ""

echo "STEP 4: Test New Filesystem"
echo "---------------------------"
echo "1. Restart the service:"
echo "   sudo systemctl restart review-platform"
echo ""
echo "2. Test GPU processing:"
echo "   cd /opt/review-platform"
echo "   ./scripts/test_nfs_gpu.sh"
echo ""

echo "💡 Why this should work:"
echo "- Fresh filesystem = no accumulated volume limits"
echo "- Clean slate for API quotas"
echo "- Reset any account-specific limits tied to the old filesystem"
echo ""
echo "🎯 Expected outcome:"
echo "- GPU instances should create successfully"
echo "- NFS mounting should work without volume limit errors"